### PR TITLE
Testcase logs

### PR DESCRIPTION
**Pull request by hbtran**
Added project structure in README. See kabanero-foundation#197

### CODE REVIEW

**Review by tomlinkusa — APPROVED** [review]

**Review by stevenschader — COMMENTED** [review]
This is the logging syntax using the ansible automation to redirect stdout/stderr to some known log location
https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/blob/445902480132c4056f8283c10b25c61d42d679e5/automation/ansible-playbooks/roles/kabanero_regression_tests/tasks/kabRegressionTest.yml#L8

Will the maintest.sh driver be updated to include this type of syntax as well?

**Comment by tomlinkusa** [comment]
I think the current logging is controlled by the code in icpa-system-test.

**Comment by hbtran** [comment]
I'm thinking the kabanero_regression_tests role is duplicating a lot of the maintest.sh.  Perhaps we can move the logging logic to maintest.sh so sandbox regression users get the logging and the role can call maintest.sh directly.

**Review by jahein — APPROVED** [review]

**Comment by stevenschader** [comment]
@hbtran   I'm working on this issue #570 which will loop over the list of repos using the XXXX-test.yml|sh syntax in the ansible automation.  I'm not sure we want to require a maintest.sh in each repo...

**Comment by hbtran** [comment]
@stevenschader Yes I will update the maintest.sh to tee the standard out and error the same way as ansible (since you think that's appropriate).

**Pull request merged**
